//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebApplication1.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Chuyen
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Chuyen()
        {
            this.LichTrinh_Tram = new HashSet<LichTrinh_Tram>();
            this.Xes = new HashSet<Xe>();
        }
    
        public string MaChuyen { get; set; }
        public string TenChuyen { get; set; }
        public string DiemBatDau { get; set; }
        public string DiemDen { get; set; }
        public Nullable<System.TimeSpan> TGChuyen { get; set; }
    
        public virtual TinhThanh TinhThanh { get; set; }
        public virtual TinhThanh TinhThanh1 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<LichTrinh_Tram> LichTrinh_Tram { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Xe> Xes { get; set; }
    }
}
