//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebApplication1.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class LichTrinh_Tram
    {
        public System.DateTime TGdukien { get; set; }
        public string MaChuyen { get; set; }
        public string MaTram { get; set; }
    
        public virtual Chuyen Chuyen { get; set; }
        public virtual Tram Tram { get; set; }
    }
}
