//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebApplication1.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class QLBenXeEntities : DbContext
    {
        public QLBenXeEntities()
            : base("name=QLBenXeEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Chuyen> Chuyens { get; set; }
        public virtual DbSet<DichVu> DichVus { get; set; }
        public virtual DbSet<Ghe> Ghes { get; set; }
        public virtual DbSet<HangXe> HangXes { get; set; }
        public virtual DbSet<Khach> Khaches { get; set; }
        public virtual DbSet<LichTrinh_Tram> LichTrinh_Tram { get; set; }
        public virtual DbSet<LoaiXe> LoaiXes { get; set; }
        public virtual DbSet<NhanVien> NhanViens { get; set; }
        public virtual DbSet<TinhThanh> TinhThanhs { get; set; }
        public virtual DbSet<Tram> Trams { get; set; }
        public virtual DbSet<Ve> Ves { get; set; }
        public virtual DbSet<Xe> Xes { get; set; }
    }
}
