//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebApplication1.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Ve
    {
        public string MaVe { get; set; }
        public Nullable<System.DateTime> NgayDat { get; set; }
        public string TrangThai { get; set; }
        public string MaKhach { get; set; }
        public string SoGhe { get; set; }
        public string Xe { get; set; }
    
        public virtual Ghe Ghe { get; set; }
        public virtual Khach Khach { get; set; }
    }
}
