//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebApplication1.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Xe
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Xe()
        {
            this.Ghes = new HashSet<Ghe>();
            this.DichVus = new HashSet<DichVu>();
        }
    
        public string MaXe { get; set; }
        public string SoXe { get; set; }
        public string MaChuyen { get; set; }
        public string TenTaiXe { get; set; }
        public string LoaiXe { get; set; }
        public string TrangThai { get; set; }
        public string MaHangXe { get; set; }
        public Nullable<System.DateTime> TGXuatPhat { get; set; }
        public Nullable<System.TimeSpan> TGHuyVe { get; set; }
        public Nullable<int> Gia { get; set; }
    
        public virtual Chuyen Chuyen { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Ghe> Ghes { get; set; }
        public virtual HangXe HangXe { get; set; }
        public virtual LoaiXe LoaiXe1 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<DichVu> DichVus { get; set; }
    }
}
